mode: immediate
branchName: '${issue.number}-${issue.title}'
branches:
  - label: bug
    prefix: bugfix/
  - label: enhancement
    prefix: feature/
  - label: documentation
    prefix: docs/
  - label: devops
    prefix: devops/
  - label: '*'
autoCloseIssue: false
commentMessage: '✅ Branche créée : `${branchName}`'